### ISSUE TITLE
Not building with Carthage

### ISSUE THREAD

**Issue by Dustinschie** [comyarzaheri/Chronos-Swift#8]
I am having building issues when trying to build with Carthage

```sh
$ carthage bootstrap --platform iOS
*** Checking out Chronos-Swift at "f6c02db716bdbc5404108fc06a6e61abcef4963e"
*** Skipped building Chronos-Swift due to the error:
Dependency "Chronos-Swift" has no shared framework schemes for any of the platforms: iOS
```

Any thoughts?

**Comment by comyarzaheri** [comment]
I believe the issue is related to the Xcode project's schemes having the workspace as their container rather than the project itself. Can you try out the latest commit ([68a6762](https://github.com/comyarzaheri/Chronos-Swift/commit/68a6762a7dd5f92b8a19b3c5fa3d91de5300b8cb)) and see if that that works for you?

**Comment by Dustinschie** [comment]
The scheme now builds without an issue. 

Thanks!
